services:
  - type: web
    name: claimsure-api
    runtime: python
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn ClaimSure_backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromDatabase:
          name: claimsure-db
          property: connectionString

databases:
  - name: claimsure-db
    databaseName: claimsure_db
    user: claimsure_user
    plan: free
